<?php
namespace Image\Reader;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-30 at 11:00:21.
 */
class DefaultReaderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DefaultReader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DefaultReader;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        unset($this->object);
    }

    /**
     * @covers Image\Reader\DefaultReader::read
     */
    public function testRead()
    {
        $image = $this->object->read('image.png');
        
        $this->assertTrue(($image && 'gd' == get_resource_type($image)));
        
    }
}
