<?php
namespace Image\Reader\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-30 at 11:00:20.
 */
class JpegTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Jpeg
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Jpeg;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        unset($this->object);
    }

    /**
     * @covers Image\Reader\Adapter\Jpeg::getImage
     */
    public function testGetImage()
    {
        $image = $this->object->getImage('image.jpg');
        $this->assertTrue(($image && 'gd' == get_resource_type($image)));
    }
}
